# Generated by Django 2.0.7 on 2018-07-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('N', 'NotOrderedYet'), ('O', 'Ordered'), ('I', 'Cooking'), ('R', 'Ready'), ('D', 'Delivered')], max_length=1),
        ),
    ]
